# Generated by Django 5.1.7 on 2025-05-28 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=150)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='LogTransacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'logs_transacoes',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
