sonar.projectKey=cam-ia-manager
sonar.projectName=CamIA Manager - Backend
sonar.projectVersion=1.0

sonar.sources=./backend/api

sonar.tests=./backend/api/tests.py

sonar.exclusions=**/migrations/**, **/venv/**, backend/api/tests.py

sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.host.url=http://host.docker.internal:9000
sonar.login=

sonar.projectBaseDir=.